
#ifndef PANEL_EVENTS_H
#define PANEL_EVENTS_H

#include "peripheral_events.h"

typedef enum
{
    PANEL_EVENT_IDLE = PERIPHERAL_EVENT_IDLE,

    PANEL_EVENT_ONOFF_PRESS = PERIPHERAL_EVENT_ONOFF_PRESS,
    PANEL_EVENT_ONOFF_PRESS_HOLD = PERIPHERAL_EVENT_ONOFF_PRESS_HOLD,
    PANEL_EVENT_ONOFF_PRESS_DOUBLE = PERIPHERAL_EVENT_ONOFF_PRESS_DOUBLE,
    PANEL_EVENT_ONOFF_RELEASE = PERIPHERAL_EVENT_ONOFF_RELEASE,

    PANEL_EVENT_LEVEL_PRESS = PERIPHERAL_EVENT_LEVEL_PRESS,
    PANEL_EVENT_LEVEL_PRESS_DOUBLE = PERIPHERAL_EVENT_LEVEL_PRESS_DOUBLE,
    PANEL_EVENT_LEVEL_PRESS_HOLD = PERIPHERAL_EVENT_LEVEL_PRESS_HOLD,
    PANEL_EVENT_LEVEL_RELEASE = PERIPHERAL_EVENT_LEVEL_RELEASE,
    PANEL_EVENT_LEVEL_CW = PERIPHERAL_EVENT_LEVEL_CW,
    PANEL_EVENT_LEVEL_CCW = PERIPHERAL_EVENT_LEVEL_CCW,

    PANEL_EVENT_CAMERA_PRESS = PERIPHERAL_EVENT_CAMERA_PRESS,
    PANEL_EVENT_CAMERA_PRESS_DOUBLE = PERIPHERAL_EVENT_CAMERA_PRESS_DOUBLE,
    PANEL_EVENT_CAMERA_PRESS_HOLD = PERIPHERAL_EVENT_CAMERA_PRESS_HOLD,
    PANEL_EVENT_CAMERA_RELEASE = PERIPHERAL_EVENT_CAMERA_RELEASE,

    PANEL_EVENT_1_PRESS = PERIPHERAL_EVENT_1_PRESS,
    PANEL_EVENT_1_PRESS_DOUBLE = PERIPHERAL_EVENT_1_PRESS_DOUBLE,
    PANEL_EVENT_1_PRESS_HOLD = PERIPHERAL_EVENT_1_PRESS_HOLD,
    PANEL_EVENT_1_RELEASE = PERIPHERAL_EVENT_1_RELEASE,

    PANEL_EVENT_2_PRESS = PERIPHERAL_EVENT_2_PRESS,
    PANEL_EVENT_2_PRESS_DOUBLE = PERIPHERAL_EVENT_2_PRESS_DOUBLE,
    PANEL_EVENT_2_PRESS_HOLD = PERIPHERAL_EVENT_2_PRESS_HOLD,
    PANEL_EVENT_2_RELEASE = PERIPHERAL_EVENT_2_RELEASE,

    PANEL_EVENT_3_PRESS = PERIPHERAL_EVENT_3_PRESS,
    PANEL_EVENT_3_PRESS_DOUBLE = PERIPHERAL_EVENT_3_PRESS_DOUBLE,
    PANEL_EVENT_3_PRESS_HOLD = PERIPHERAL_EVENT_3_PRESS_HOLD,
    PANEL_EVENT_3_RELEASE = PERIPHERAL_EVENT_3_RELEASE,

    PANEL_EVENT_FUNCTION_PRESS = PERIPHERAL_EVENT_FUNCTION_PRESS,
    PANEL_EVENT_FUNCTION_PRESS_DOUBLE = PERIPHERAL_EVENT_FUNCTION_PRESS_DOUBLE,
    PANEL_EVENT_FUNCTION_PRESS_HOLD = PERIPHERAL_EVENT_FUNCTION_PRESS_HOLD,
    PANEL_EVENT_FUNCTION_RELEASE = PERIPHERAL_EVENT_FUNCTION_RELEASE,
    PANEL_EVENT_FUNCTION_CW = PERIPHERAL_EVENT_FUNCTION_CW,
    PANEL_EVENT_FUNCTION_CCW = PERIPHERAL_EVENT_FUNCTION_CCW,

    PANEL_EVENT_SYSTEM_BOOT,
    PANEL_EVENT_SYSTEM_SHUTDOWN,

} PanelEvent;

typedef enum
{
    SYSTEM_EVENT_IDLE,

    SYSTEM_EVENT_OFF,
    SYSTEM_EVENT_ON,

    SYSTEM_EVENT_LIGHT_GREEN_SOLID,
    SYSTEM_EVENT_LIGHT_GREEN_FLASH,
    SYSTEM_EVENT_LIGHT_GREEN_FLASH_FAST,
    SYSTEM_EVENT_LIGHT_YELLOW_SOLID,
    SYSTEM_EVENT_LIGHT_YELLOW_FLASH,
    SYSTEM_EVENT_LIGHT_YELLOW_FLASH_FAST,
    SYSTEM_EVENT_LIGHT_RED_SOLID,
    SYSTEM_EVENT_LIGHT_RED_FLASH,
    SYSTEM_EVENT_LIGHT_RED_FLASH_FAST,
    SYSTEM_EVENT_LIGHT_OFF,
} SystemEvent;

#endif // PANEL_EVENTS_H