
#ifndef PANEL_EVENTS_H
#define PANEL_EVENTS_H

#include "peripheral_events.h"

typedef enum {
    PANEL_EVENT_IDLE = PERIPHERAL_EVENT_IDLE,

    PANEL_EVENT_ONOFF_PRESS = PERIPHERAL_EVENT_ONOFF_PRESS,
    PANEL_EVENT_ONOFF_PRESS_HOLD = PERIPHERAL_EVENT_ONOFF_PRESS_HOLD,
    PANEL_EVENT_ONOFF_PRESS_DOUBLE = PERIPHERAL_EVENT_ONOFF_PRESS_DOUBLE,
    PANEL_EVENT_ONOFF_RELEASE = PERIPHERAL_EVENT_ONOFF_RELEASE,

    PANEL_EVENT_FUNCTION_PRESS = PERIPHERAL_EVENT_FUNCTION_PRESS,
	PANEL_EVENT_FUNCTION_PRESS_DOUBLE = PERIPHERAL_EVENT_FUNCTION_PRESS_DOUBLE,
	PANEL_EVENT_FUNCTION_PRESS_HOLD = PERIPHERAL_EVENT_FUNCTION_PRESS_HOLD,
	PANEL_EVENT_FUNCTION_RELEASE = PERIPHERAL_EVENT_FUNCTION_RELEASE,
	PANEL_EVENT_FUNCTION_CW = PERIPHERAL_EVENT_FUNCTION_CW,
	PANEL_EVENT_FUNCTION_CCW = PERIPHERAL_EVENT_FUNCTION_CCW,

    PANEL_EVENT_COLOR_ARTIFICIAL_PRESS = PERIPHERAL_EVENT_COLOR_ARTIFICIAL_PRESS,	
	PANEL_EVENT_COLOR_ARTIFICIAL_PRESS_DOUBLE = PERIPHERAL_EVENT_COLOR_ARTIFICIAL_PRESS_DOUBLE,
	PANEL_EVENT_COLOR_ARTIFICIAL_PRESS_HOLD = PERIPHERAL_EVENT_COLOR_ARTIFICIAL_PRESS_HOLD,
	PANEL_EVENT_COLOR_ARTIFICIAL_RELEASE = PERIPHERAL_EVENT_COLOR_ARTIFICIAL_RELEASE,

    PANEL_EVENT_COLOR_NATURAL_PRESS = PERIPHERAL_EVENT_COLOR_NATURAL_PRESS,	
    PANEL_EVENT_COLOR_NATURAL_PRESS_DOUBLE = PERIPHERAL_EVENT_COLOR_NATURAL_PRESS_DOUBLE,
    PANEL_EVENT_COLOR_NATURAL_PRESS_HOLD = PERIPHERAL_EVENT_COLOR_NATURAL_PRESS_HOLD,
    PANEL_EVENT_COLOR_NATURAL_RELEASE = PERIPHERAL_EVENT_COLOR_NATURAL_RELEASE,

    PANEL_EVENT_ZOOM_PRESS = PERIPHERAL_EVENT_ZOOM_PRESS,
	PANEL_EVENT_ZOOM_PRESS_DOUBLE = PERIPHERAL_EVENT_ZOOM_PRESS_DOUBLE,
	PANEL_EVENT_ZOOM_PRESS_HOLD = PERIPHERAL_EVENT_ZOOM_PRESS_HOLD,
	PANEL_EVENT_ZOOM_RELEASE = PERIPHERAL_EVENT_ZOOM_RELEASE,
	PANEL_EVENT_ZOOM_CW = PERIPHERAL_EVENT_ZOOM_CW,
	PANEL_EVENT_ZOOM_CCW = PERIPHERAL_EVENT_ZOOM_CCW,

    PANEL_EVENT_SYSTEM_BOOT,
    PANEL_EVENT_SYSTEM_SHUTDOWN,
    
} PanelEvent;

typedef enum {
    SYSTEM_EVENT_IDLE,

    SYSTEM_EVENT_OFF,
    SYSTEM_EVENT_ON,

    SYSTEM_EVENT_LIGHT_GREEN_SOLID,
    SYSTEM_EVENT_LIGHT_GREEN_FLASH,
    SYSTEM_EVENT_LIGHT_GREEN_FLASH_FAST,
    SYSTEM_EVENT_LIGHT_YELLOW_SOLID,
    SYSTEM_EVENT_LIGHT_YELLOW_FLASH,
    SYSTEM_EVENT_LIGHT_YELLOW_FLASH_FAST,
    SYSTEM_EVENT_LIGHT_RED_SOLID,
    SYSTEM_EVENT_LIGHT_RED_FLASH,
    SYSTEM_EVENT_LIGHT_RED_FLASH_FAST,
    SYSTEM_EVENT_LIGHT_OFF,
} SystemEvent;

#endif // PANEL_EVENTS_H