
#include "peripherals.h"
#include "lights.h"
#include "tim.h"
#include "i2c.h"


typedef enum {
    PANEL_EVENT_IDLE = PERIPHERAL_EVENT_IDLE,

    PANEL_EVENT_ONOFF_PRESS = PERIPHERAL_EVENT_ONOFF_PRESS,
    PANEL_EVENT_ONOFF_PRESS_HOLD = PERIPHERAL_EVENT_ONOFF_PRESS_HOLD,
    PANEL_EVENT_ONOFF_PRESS_DOUBLE = PERIPHERAL_EVENT_ONOFF_PRESS_DOUBLE,

    PANEL_EVENT_FUNCTION_PRESS = PERIPHERAL_EVENT_FUNCTION_PRESS,
	PANEL_EVENT_FUNCTION_PRESS_DOUBL = PERIPHERAL_EVENT_FUNCTION_PRESS_DOUBLE,
	PANEL_EVENT_FUNCTION_PRESS_HOLD = PERIPHERAL_EVENT_FUNCTION_PRESS_HOLD,
	PANEL_EVENT_FUNCTION_UP = PERIPHERAL_EVENT_FUNCTION_UP,
	PANEL_EVENT_FUNCTION_DN = PERIPHERAL_EVENT_FUNCTION_DN,

    PANEL_EVENT_COLOR_ARTIFICIAL_PRESS = PERIPHERAL_EVENT_COLOR_ARTIFICIAL_PRESS,	
	PANEL_EVENT_COLOR_ARTIFICIAL_PRESS_DOUBLE = PERIPHERAL_EVENT_COLOR_ARTIFICIAL_PRESS_DOUBLE,
	PANEL_EVENT_COLOR_ARTIFICIAL_PRESS_HOLD = PERIPHERAL_EVENT_COLOR_ARTIFICIAL_PRESS_HOLD,

    PANEL_EVENT_COLOR_NATURAL_PRESS = PERIPHERAL_EVENT_COLOR_NATURAL_PRESS,	
    PANEL_EVENT_COLOR_NATURAL_PRESS_DOUBLE = PERIPHERAL_EVENT_COLOR_NATURAL_PRESS_DOUBLE,
    PANEL_EVENT_COLOR_NATURAL_PRESS_HOLD = PERIPHERAL_EVENT_COLOR_NATURAL_PRESS_HOLD,

    PANEL_EVENT_ZOOM_PRESS = PERIPHERAL_EVENT_ZOOM_PRESS,
	PANEL_EVENT_ZOOM_PRESS_DOUBL = PERIPHERAL_EVENT_ZOOM_PRESS_DOUBLE,
	PANEL_EVENT_ZOOM_PRESS_HOLD = PERIPHERAL_EVENT_ZOOM_PRESS_HOLD,
	PANEL_EVENT_ZOOM_UP = PERIPHERAL_EVENT_ZOOM_UP,
	PANEL_EVENT_ZOOM_DN = PERIPHERAL_EVENT_ZOOM_DN,

    PANEL_EVENT_SYSTEM_BOOT,
    PANEL_EVENT_SYSTEM_SHUTDOWN,
    
} PanelEvent;

typedef enum {
    SYSTEM_EVENT_IDLE,

    SYSTEM_EVENT_OFF,
    SYSTEM_EVENT_ON
} SystemEvent;

typedef enum {
    SYSTEM_STATE_OFF = 1,
    SYSTEM_STATE_BOOT,
    SYSTEM_STATE_ON,
    SYSTEM_STATE_SHUTDOWN
} SystemState;

void Panel_Init();
void Panel_Scan();

void Panel_HandleEventPeripherals();