#ifndef PERIPHERAL_EVENTS_H
#define PERIPHERAL_EVENTS_H

typedef enum
{
	PERIPHERAL_EVENT_IDLE,

	PERIPHERAL_EVENT_ONOFF_PRESS = 1,
	PERIPHERAL_EVENT_ONOFF_PRESS_DOUBLE,
	PERIPHERAL_EVENT_ONOFF_PRESS_HOLD,
	PERIPHERAL_EVENT_ONOFF_RELEASE,

	PERIPHERAL_EVENT_LEVEL_PRESS,
	PERIPHERAL_EVENT_LEVEL_PRESS_DOUBLE,
	PERIPHERAL_EVENT_LEVEL_PRESS_HOLD,
	PERIPHERAL_EVENT_LEVEL_RELEASE,
	PERIPHERAL_EVENT_LEVEL_CW,
	PERIPHERAL_EVENT_LEVEL_CCW,

	PERIPHERAL_EVENT_CAMERA_PRESS,
	PERIPHERAL_EVENT_CAMERA_PRESS_DOUBLE,
	PERIPHERAL_EVENT_CAMERA_PRESS_HOLD,
	PERIPHERAL_EVENT_CAMERA_RELEASE,

	PERIPHERAL_EVENT_1_PRESS,
	PERIPHERAL_EVENT_1_PRESS_DOUBLE,
	PERIPHERAL_EVENT_1_PRESS_HOLD,
	PERIPHERAL_EVENT_1_RELEASE,

	PERIPHERAL_EVENT_2_PRESS,
	PERIPHERAL_EVENT_2_PRESS_DOUBLE,
	PERIPHERAL_EVENT_2_PRESS_HOLD,
	PERIPHERAL_EVENT_2_RELEASE,

	PERIPHERAL_EVENT_3_PRESS,
	PERIPHERAL_EVENT_3_PRESS_DOUBLE,
	PERIPHERAL_EVENT_3_PRESS_HOLD,
	PERIPHERAL_EVENT_3_RELEASE,

	PERIPHERAL_EVENT_FUNCTION_PRESS,
	PERIPHERAL_EVENT_FUNCTION_PRESS_DOUBLE,
	PERIPHERAL_EVENT_FUNCTION_PRESS_HOLD,
	PERIPHERAL_EVENT_FUNCTION_RELEASE,
	PERIPHERAL_EVENT_FUNCTION_CW,
	PERIPHERAL_EVENT_FUNCTION_CCW

} PeripheralEvent;

#endif // PERIPHERAL_EVENTS_H