#ifndef PERIPHERAL_EVENTS_H
#define PERIPHERAL_EVENTS_H


typedef enum {
	PERIPHERAL_EVENT_IDLE,

	PERIPHERAL_EVENT_ONOFF_PRESS = 1,	
	PERIPHERAL_EVENT_ONOFF_PRESS_DOUBLE,
	PERIPHERAL_EVENT_ONOFF_PRESS_HOLD,
	PERIPHERAL_EVENT_ONOFF_RELEASE,

	PERIPHERAL_EVENT_FUNCTION_PRESS,
	PERIPHERAL_EVENT_FUNCTION_PRESS_DOUBLE,
	PERIPHERAL_EVENT_FUNCTION_PRESS_HOLD,
	PERIPHERAL_EVENT_FUNCTION_RELEASE,
	PERIPHERAL_EVENT_FUNCTION_CW,
	PERIPHERAL_EVENT_FUNCTION_CCW,

	PERIPHERAL_EVENT_COLOR_ARTIFICIAL_PRESS,	
	PERIPHERAL_EVENT_COLOR_ARTIFICIAL_PRESS_DOUBLE,
	PERIPHERAL_EVENT_COLOR_ARTIFICIAL_PRESS_HOLD,
	PERIPHERAL_EVENT_COLOR_ARTIFICIAL_RELEASE,

	PERIPHERAL_EVENT_COLOR_NATURAL_PRESS,
	PERIPHERAL_EVENT_COLOR_NATURAL_PRESS_DOUBLE,
	PERIPHERAL_EVENT_COLOR_NATURAL_PRESS_HOLD,
	PERIPHERAL_EVENT_COLOR_NATURAL_RELEASE,

	PERIPHERAL_EVENT_ZOOM_PRESS,
	PERIPHERAL_EVENT_ZOOM_PRESS_DOUBLE,
	PERIPHERAL_EVENT_ZOOM_PRESS_HOLD,
	PERIPHERAL_EVENT_ZOOM_RELEASE,
	PERIPHERAL_EVENT_ZOOM_CW,
	PERIPHERAL_EVENT_ZOOM_CCW
	
} PeripheralEvent;

#endif // PERIPHERAL_EVENTS_H