/*
 * peripherals.h
 *
 *  Created on: 28 okt. 2022
 *      Author: mb2
 */

#ifndef INC_PERIPHERALS_H_
#define INC_PERIPHERALS_H_

#include "stdint.h"
#include "stm32f0xx_hal.h"
#include "timer.h"
#include "gpio.h"
#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "peripheral_events.h"

#define CONCAT_ENC_READ(ap, a, bp, b) ((ap<<3) | (a<<2) | (bp<<1) | (b))
#define CONCAT_BTN_READ(sp, s) ((sp<<1) | (s))

#define MAX_AMT_ENCS 		3 /* Maximum amount of buttons allowed */
#define MAX_AMT_BTNS 		6 /* Maximum amount of buttons allowed */

#define PERIPHERAL_NOT_INIT		0x00 /* FLAG: Peripheral not initialized */
#define PERIPHERAL_INIT			0x01 /* FLAG: Peripheral initialized */

/* Uncomment when using firmware based double-clicks and hold events */
// #define PERIPHERAL_SPECIAL_EVENTS

#define PERIPHERAL_HOLD_TIME 	5100 /* ms */
#define PERIPHERAL_PRESS_DOUBLE_TIME 350 /* ms */
off_t
extern PeripheralEvent peripheralEvent;

enum {
	PERIPHERAL_EVENT_ID_PRESS,
	PERIPHERAL_EVENT_ID_PRESS_HOLD,
	PERIPHERAL_EVENT_ID_PRESS_DOUBLE,
	PERIPHERAL_EVENT_ID_RELEASE
};

typedef enum {
	BTN_ID_ONOFF = 0x01,
	BTN_ID_FUNCTION = 0x02,
	BTN_ID_ZOOM = 0x03,
	BTN_ID_COLOR_NATURAL = 0x04,
	BTN_ID_COLOR_ARTIFICIAL = 0x05,

	ENC_ID_FUNCTION = 0x01,
	ENC_ID_ZOOM	= 0x02,
} PeripheralID;

typedef enum{
	BTN_MODE_LO = 0x00, /* Defines a button as active-low */
	BTN_MODE_HI = 0x01 /* Defines a button as active-high */
} ButtonMode;

/* The table below shows the states of an active-low button.
 * The signals below will be concatenated in the order that they are shown, creating a 2-bit pattern.
 *
 * btn_sig_prev		btn->sig		btn->state
 * 		1				1		BTN_STATE_RST 	(active-low)
 * 		0				0		BTN_STATE_RST	(active-high)
 * 		--------------------------------------------------
 * 		1				0		BTN_STATE_PRESS	(active-low)
 * 		0				1		BTN_STATE_PRESS	(active-high)
 * 		--------------------------------------------------
 * 		0				0		BTN_STATE_HOLD	(active-low)
 * 		1				1		BTN_STATE_HOLD	(active-high)
 * 		--------------------------------------------------
 * 		0				1		BTN_STATE_REL	(active-low)
 * 		1				0		BTN_STATE_REL	(active-high)
 *		*/

typedef enum{
	BTN_LO_RST		= 0b11,
	BTN_HI_RST		= 0b00,
	BTN_LO_PRESS	= 0b10,
	BTN_HI_PRESS	= 0b01,
	BTN_LO_HOLD		= 0b00,
	BTN_HI_HOLD		= 0b11,
	BTN_LO_REL		= 0b01,
	BTN_HI_REL		= 0b10
} ButtonSignal;

typedef enum{
	BTN_STATE_RST, 
	BTN_STATE_PRESS,
	BTN_STATE_HOLD,
	BTN_STATE_REL
} ButtonState;

/**@brief Push-button container */
typedef struct {
	PeripheralID id;			/* Button identifier - Used when determining what commands shall be generated by button actions */
	uint8_t mode;		/* Defines the button as active low, or active high */
	uint8_t init_flag;	/* Flags if encoder is initialized (PERIPH_INIT) or not (PERIPH_NOT_INIT) */
	uint8_t state; 		/* Button state variable */
	uint8_t sig;		/* Button signal variable */

	GPIO_TypeDef *PORT;	/* Button port */
	uint16_t PIN; 		/* Button input pin */

	Timer timer_hold;
	Timer timer_press;
	Timer timer_press_double;
} Button;

void periphButtonInit(Button *btn, PeripheralID id, uint8_t type, GPIO_TypeDef *PORT, uint16_t PIN);
void periphButtonScan(Button *btn);
void periphButtonExec(Button *btn);

/* ENCODER DEFINITIONS */

/* Example: If an encoder has 30 mechanical detents and outputs 30 pulses on one turn of the encoder shaft, the encoder is matched.
 * Inversely, if the encoder has 30 mechanical detents and outputs 15 pulses, the encoder is unmatched.*/

/* The table below shows the states of an UNMATCHED encoder based on its channels' input signals.
 * The signals below will be concatenated in the order that they are shown, creating a 4-bit pattern.
 *
 * enc_ch_a_prev	enc->ch_a	enc_ch_b_prev		enc->ch_b	enc->state
 * 		1				1				1				1		ENC_STATE_RST
 * 		0				0				0				0		ENC_STATE_RST
 * 		--------------------------------------------------
 * 		0				0				1				0		ENC_STATE_CW
 * 		1				1				0				1		ENC_STATE_CW
 * 		--------------------------------------------------
 * 		1				0				0				0		ENC_STATE_CCW
 * 		0				1				1				1		ENC_STATE_CCW
 * 		*/

/* The table below shows the states of an MATCHED encoder based on its channels' input signals.
 *
 * enc_ch_a_prev	enc->ch_a	enc_ch_b_prev		enc->ch_b	enc->state
 * 		1				1				1				1		ENC_STATE_RST
 * 		0				0				0				0		ENC_STATE_RST
 * 		--------------------------------------------------
 * 		0				0				1				0		ENC_STATE_CW
 * 		--------------------------------------------------
 * 		1				0				0				0		ENC_STATE_CCW
 * 		*/

typedef enum{
	ENC_RST1 	= 0b0000, /** Reset pattern (1) for UNMATCHED and MATCHED encoders */
	ENC_RST2 	= 0b1111, /** Reset pattern (2) for UNMATCHED and MATCHED encoders */

	ENC_CW1 	= 0b0010, /** Clock-wise pattern (1) for UNMATCHED and MATCHED encoders */
	ENC_CW2 	= 0b1101,  /** Clock-wise pattern (2) for UNMATCHED encoders */

	ENC_CCW1 	= 0b1000, /** Counter clock-wise pattern (1) for UNMATCHED and MATCHED encoders */
	ENC_CCW2 	= 0b0111,  /** Counter clock-wise pattern (2) for only UNMATCHED encoders */
} EncoderSignal;

typedef enum{
	ENC_STATE_RST, /** Reset state for encoder */
	ENC_STATE_CW,  /** Clock-wise state for encoder */
	ENC_STATE_CCW  /** Counter clock-wise state for encoder */
} EncoderState;

typedef enum{
	ENC_MODE_UNMATCHED = 0x02, /* Panel uses encoders with unmatched detents and PPR (Pulses Per Rotation) */
	ENC_MODE_MATCHED = 0x01 /* Panel uses encoders with matched detents and PPR (Pulses Per Rotation) */
} EncoderMode;

/**@brief Incremental encoder container */
typedef struct {
	PeripheralID id;						/* Encoder identifier - Used when determining what commands shall be generated by encoder actions */
	EncoderMode mode; 					/* Defines the encoder as matched or unmatched */
	uint8_t init_flag;				/* Flags if encoder is initialized (PERIPH_INIT) or not (PERIPH_NOT_INIT) */
	EncoderState state;					/* Encoder state-machine */
	uint8_t ch_a, ch_b;				/* Encoder channel variables*/

	GPIO_TypeDef *PORT_A, *PORT_B; 	/* Encoder channels' ports */
	uint16_t PIN_A, PIN_B; 			/* Encoder channels' input pins */
} Encoder;

void Peripheral_EncoderInit(Encoder *enc, PeripheralID id, EncoderMode mode, GPIO_TypeDef *PORT_A, uint16_t PIN_A, GPIO_TypeDef *PORT_B, uint16_t PIN_B);
void Peripheral_EncoderScan(Encoder *enc);
void Peripheral_EncoderExec(Encoder *enc);


/**Panel system container */
typedef struct PeripheralGroup{
//	uint8_t id;					/* Defined panel ID (see "Panel ID variants") */
//	uint8_t state;				/* State of the panel (see "Panel states") */

//	uint8_t event_buff[16];

	Button btn[MAX_AMT_BTNS];	/* Panel buttons */
	Encoder enc[MAX_AMT_ENCS];	/* Panel encoders */
} PeripheralGroup;

void Peripheral_InitGroup(void);
void Peripheral_ScanGroup(void);

#endif /* INC_PERIPHERALS_H_ */
